In [1]:
!pip -q install pandas beautifulsoup4 requests openpyxl lxml html5lib

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

In [4]:
URL = "https://chennai.vit.ac.in/freshers-induction-programme-2026/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

response = requests.get(
    URL,
    headers=headers,
    verify=False,
    timeout=30
)

print("Status Code:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

rows = soup.find_all("tr")

departments = []

for row in rows:

    cols = row.find_all("td")

    if len(cols) < 6:
        continue

    department = cols[0].get_text(" ", strip=True)
    reporting_date = cols[1].get_text(" ", strip=True)
    orientation_date = cols[2].get_text(" ", strip=True)
    reporting_time = cols[3].get_text(" ", strip=True)
    venue = cols[4].get_text(" ", strip=True)

    link = cols[5].find("a")

    schedule_url = ""

    if link:
        schedule_url = urljoin(URL, link["href"])

    departments.append({
        "Department": department,
        "Reporting Date": reporting_date,
        "Orientation Date": orientation_date,
        "Reporting Time": reporting_time,
        "Venue": venue,
        "Schedule URL": schedule_url
    })

dept_df = pd.DataFrame(departments)

print("Departments Found:", len(dept_df))

dept_df.head()

Status Code: 200
Departments Found: 20

,Department,Reporting Date,Orientation Date,Reporting Time,Venue,Schedule URL
0,B.Tech. Biotechnology,14 Jul 2026,15 Jul 2026,8.30 AM,MG Auditorium,https://chennai.vit.ac.in/b-tech-bio-technology/
1,B.Tech. Civil Engineering,14 Jul 2026,15 Jul 2026,8.30 AM,MG Auditorium,https://chennai.vit.ac.in/school-of-civil-engi...
2,B.Tech. Civil Engineering (In Collaboration wi...,14 Jul 2026,15 Jul 2026,8.30 AM,MG Auditorium,https://chennai.vit.ac.in/school-of-civil-engi...
3,B.Tech. Electrical and Computer Science Engine...,14 Jul 2026,15 Jul 2026,8.30 AM,MG Auditorium,https://chennai.vit.ac.in/school-of-electrical...
4,B.Tech. Electrical and Electronics Engineering,14 Jul 2026,15 Jul 2026,8.30 AM,MG Auditorium,https://chennai.vit.ac.in/school-of-electrical...

In [6]:
writer = pd.ExcelWriter(
    "Freshers_Induction_2026.xlsx",
    engine="openpyxl"
)

# Save department list
dept_df.to_excel(
    writer,
    sheet_name="Department List",
    index=False
)

print("="*60)

for i, row in dept_df.iterrows():

    department = row["Department"]
    url = row["Schedule URL"]

    print(f"{i+1}. {department}")

    if url == "":
        print("   No schedule URL")
        continue

    try:

        # Read all HTML tables
        html = requests.get(
          url,
          headers=headers,
          verify=False,
          timeout=30).text
        tables = pd.read_html(html)

        if len(tables) == 0:
            print("   No HTML table found")
            continue

        # Usually first table contains schedule
        schedule = tables[0]

        # Excel sheet names max 31 chars
        sheet_name = department[:31]

        schedule.to_excel(
            writer,
            sheet_name=sheet_name,
            index=False
        )

        print("   Saved")

    except Exception as e:
        print("   Error:", e)

writer.close()

print("\nExcel file created successfully!")

============================================================
1. B.Tech. Biotechnology

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
2. B.Tech. Civil Engineering

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
3. B.Tech. Civil Engineering (In Collaboration with L&T)

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
4. B.Tech. Electrical and Computer Science Engineering

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
5. B.Tech. Electrical and Electronics Engineering

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
6. B.Tech. Mechanical Engineering

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
7. B.Tech. Mechanical Engineering (Electric Vehicles)

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
8. B.Tech. Mechatronics and Automation

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
9. B.Tech. Fashion Technology

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
10. B.Tech. Computer Science and Engineering 26BCE1XXX Series

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
11. B.Tech. Computer Science and Engineering 26BCE5XXX Series

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
12. B.Tech. CSE (Artificial Intelligence and Machine Learning)

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
13. B.Tech. CSE (Cyber Security) – 2+2 Dual Degree

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
14. B.Tech. CSE (Quantum Computing)

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
15. B.Tech. CSE (Data Science)

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
16. B.Tech. CSE (Cyber Security)

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
17. B.Tech. CSE (Artificial Intelligence and Robotics)

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
18. B.Tech. Electronics and Communication Engineering

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
19. B.Tech. Electronics and Computer Engineering

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

   Saved
20. B.Tech. Electronics Engineering (VLSI Design and Technology)
   Saved

Excel file created successfully!

/tmp/ipykernel_507/2254073391.py:34: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

In [8]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

session = requests.Session()
session.verify = False

headers = {
    "User-Agent": "Mozilla/5.0"
}

In [9]:
all_data = []

for index, row in dept_df.iterrows():

    department = row["Department"]
    url = row["Schedule URL"]

    print(f"Processing: {department}")

    try:
        response = session.get(url, headers=headers, timeout=30)
        soup = BeautifulSoup(response.text, "html.parser")

        table = soup.find("table", class_="wp-acad-sched-table")

        if table is None:
            print("  No schedule table found.")
            continue

        tbody = table.find("tbody")

        for tr in tbody.find_all("tr"):

            cols = tr.find_all("td")

            if len(cols) != 5:
                continue

            all_data.append({
                "Department": department,
                "Date": cols[0].get_text(strip=True),
                "Day": cols[1].get_text(strip=True),
                "Time": cols[2].get_text(strip=True),
                "Details": cols[3].get_text(" ", strip=True),
                "Venue": cols[4].get_text(" ", strip=True)
            })

        print("  Done")

    except Exception as e:
        print("  Error:", e)

Processing: B.Tech. Biotechnology
  Done
Processing: B.Tech. Civil Engineering
  Done
Processing: B.Tech. Civil Engineering (In Collaboration with L&T)
  Done
Processing: B.Tech. Electrical and Computer Science Engineering
  Done
Processing: B.Tech. Electrical and Electronics Engineering
  Done
Processing: B.Tech. Mechanical Engineering
  Done
Processing: B.Tech. Mechanical Engineering (Electric Vehicles)
  Done
Processing: B.Tech. Mechatronics and Automation
  Done
Processing: B.Tech. Fashion Technology
  Done
Processing: B.Tech. Computer Science and Engineering 26BCE1XXX Series
  Done
Processing: B.Tech. Computer Science and Engineering 26BCE5XXX Series
  Done
Processing: B.Tech. CSE (Artificial Intelligence and Machine Learning)
  Done
Processing: B.Tech. CSE (Cyber Security) – 2+2 Dual Degree
  Done
Processing: B.Tech. CSE (Quantum Computing)
  Done
Processing: B.Tech. CSE (Data Science)
  Done
Processing: B.Tech. CSE (Cyber Security)
  Done
Processing: B.Tech. CSE (Artificial Intelligence and Robotics)
  Done
Processing: B.Tech. Electronics and Communication Engineering
  Done
Processing: B.Tech. Electronics and Computer Engineering
  Done
Processing: B.Tech. Electronics Engineering (VLSI Design and Technology)
  Done

In [10]:
schedule_df = pd.DataFrame(all_data)

schedule_df.to_excel(
    "Freshers_Induction_2026_Schedule.xlsx",
    index=False
)

print(schedule_df.head())

              Department        Date        Day                 Time  \
0  B.Tech. Biotechnology  15.07.2026  Wednesday   9:30 AM - 01:00 PM
1  B.Tech. Biotechnology  15.07.2026  Wednesday  02:00 PM - 03:30 PM
2  B.Tech. Biotechnology  15.07.2026  Wednesday  03:30 PM - 05:00 PM
3  B.Tech. Biotechnology  16.07.2026   Thursday  10:00 AM - 01:00 PM
4  B.Tech. Biotechnology  16.07.2026   Thursday  02:00 PM - 04:00 PM

                              Details  \
0                      Main Induction
1                    School Induction
2             Proctor-Proctee Meeting
3            English Proficiency Test
4  Document Submission / Verification

                                            Venue
0                                   MG Auditorium
1                                  VOC Auditorium
2  Venue will be updated later in Freshers Portal
3  Venue will be updated later Freshers Info Link
4                                   Kasturba Hall

In [11]:
import pandas as pd
import json

# Read the Excel generated earlier
df = pd.read_excel("Freshers_Induction_2026_Schedule.xlsx")

df.head()

,Department,Date,Day,Time,Details,Venue
0,B.Tech. Biotechnology,15.07.2026,Wednesday,9:30 AM - 01:00 PM,Main Induction,MG Auditorium
1,B.Tech. Biotechnology,15.07.2026,Wednesday,02:00 PM - 03:30 PM,School Induction,VOC Auditorium
2,B.Tech. Biotechnology,15.07.2026,Wednesday,03:30 PM - 05:00 PM,Proctor-Proctee Meeting,Venue will be updated later in Freshers Portal
3,B.Tech. Biotechnology,16.07.2026,Thursday,10:00 AM - 01:00 PM,English Proficiency Test,Venue will be updated later Freshers Info Link
4,B.Tech. Biotechnology,16.07.2026,Thursday,02:00 PM - 04:00 PM,Document Submission / Verification,Kasturba Hall

In [12]:
from datetime import datetime

programmes = []

# Group by programme
for programme, prog_df in df.groupby("Department"):

    schedule = []

    # Group by date
    for date, date_df in prog_df.groupby("Date"):

        # Convert DD.MM.YYYY -> YYYY-MM-DD
        try:
            formatted_date = datetime.strptime(str(date), "%d.%m.%Y").strftime("%Y-%m-%d")
        except:
            formatted_date = str(date)

        slots = []

        for slot_no, (_, row) in enumerate(date_df.iterrows(), start=1):

            slots.append({
                "slot": slot_no,
                "time": row["Time"],
                "activity": row["Details"]
            })

        schedule.append({
            "date": formatted_date,
            "slots": slots
        })

    programmes.append({
        "programme": programme,
        "schedule": schedule
    })

In [13]:
with open("Freshers_Induction_2026.json", "w", encoding="utf-8") as f:
    json.dump(programmes, f, indent=2, ensure_ascii=False)

print("JSON Saved Successfully!")

JSON Saved Successfully!